"""The SDK against the ZATCA Tools production pipeline.

``fixtures/reference`` was generated by the platform that has been signing
documents ZATCA accepts in production, for the scenarios in
``fixtures/scenarios.json``. Same input, same totals, same XML, same hash,
same QR — byte for byte, except the parts that are meant to differ each time
(the signing time and the ECDSA signature, which is randomised).
"""

import base64
import json
import re

import pytest
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import ec

from zatca_tools import Zatca, decode_qr
from zatca_tools.signing.certificate import SigningIdentity

from .conftest import FIXTURES

SCENARIOS = json.loads((FIXTURES / "scenarios.json").read_text(encoding="utf-8"))["scenarios"]


def _document(spec, scenario, reference):
    d = spec["defaults"]
    # The scenarios are written in the platform's own vocabulary (form, lines,
    # billing_reference); the SDK's names for the same fields:
    document = {
        "type": scenario["form"],
        "kind": scenario.get("kind", "invoice"),
        "number": scenario["number"],
        "uuid": reference["uuid"],
        "icv": d["icv"],
        "pih": d["pih"],
        "date": d["issue_date"],
        "time": d["issue_time"],
        "prices_include_vat": scenario.get("prices_include_vat", False),
        "discount": scenario.get("discount", 0),
        "items": scenario["lines"],
    }
    for key, ours in (("billing_reference", "original_invoice"), ("reason", "reason"), ("delivery_date", "delivery_date")):
        if key in scenario:
            document[ours] = scenario[key]
    if "buyer" in scenario:
        document["buyer"] = spec["buyers"][scenario["buyer"]]
    return document


def _normalise(xml):
    xml = xml.replace("\r\n", "\n")
    xml = re.sub(r"<xades:SigningTime>[^<]*<", "<xades:SigningTime>T<", xml)
    xml = re.sub(r'(URI="#xadesSignedProperties">\s*<ds:DigestMethod[^>]*/>\s*<ds:DigestValue>)[^<]*', r"\1D", xml)
    xml = re.sub(r"<ds:SignatureValue>[^<]*<", "<ds:SignatureValue>S<", xml)
    return re.sub(r'(<cbc:ID>QR</cbc:ID>\s*<cac:Attachment>\s*<cbc:EmbeddedDocumentBinaryObject mimeCode="text/plain">)[^<]*', r"\1Q", xml)


@pytest.mark.parametrize("scenario", SCENARIOS, ids=[s["name"] for s in SCENARIOS])
def test_same_document_as_the_production_pipeline(spec, test_credentials, scenario):
    reference = json.loads((FIXTURES / "reference" / f"{scenario['name']}.json").read_text(encoding="utf-8"))
    zatca = Zatca("simulation", seller=spec["seller"], credentials=test_credentials, allowance_reason="خصم")

    document = zatca.create_invoice(_document(spec, scenario, reference))

    # The figures.
    for key, ours in (("taxable", "taxable"), ("tax", "tax"), ("grand", "total"), ("line_total", "line_total"), ("discount", "discount")):
        assert document.totals[ours] == pytest.approx(reference["totals"][key], abs=1e-9), key

    # The hash ZATCA recomputes, and the whole signed document.
    assert document.hash == reference["signed_hash"]
    expected = (FIXTURES / "reference" / f"{scenario['name']}.signed.xml").read_text(encoding="utf-8")
    assert _normalise(document.xml) == _normalise(expected)

    # The QR code, field by field (tag 7, the signature, is random by design).
    ours, theirs = decode_qr(document.qr), decode_qr(reference["qr"])
    assert set(ours) == set(theirs)
    assert {k: v for k, v in ours.items() if k != "signature"} == {k: v for k, v in theirs.items() if k != "signature"}


@pytest.mark.parametrize("scenario", SCENARIOS[:3], ids=[s["name"] for s in SCENARIOS[:3]])
def test_the_signature_verifies_against_the_certificate(spec, test_credentials, scenario):
    reference = json.loads((FIXTURES / "reference" / f"{scenario['name']}.json").read_text(encoding="utf-8"))
    document = Zatca("simulation", seller=spec["seller"], credentials=test_credentials).create_invoice(_document(spec, scenario, reference))
    identity = SigningIdentity.load(test_credentials["certificate"], test_credentials["private_key"])
    signature = re.search(r"<ds:SignatureValue>([^<]+)<", document.xml).group(1)
    identity.certificate.public_key().verify(base64.b64decode(signature), base64.b64decode(document.hash), ec.ECDSA(hashes.SHA256()))
    assert decode_qr(document.qr)["signature"] == signature
